int a = 1;
int b = 9;
int c = 5;
int d = 304;
int e = 198;
int max = a;
if (max < b) max = b;
if (max < c) max = c;
if (max < d) max = d;
if (max < e) max = e;
Console.Write("Наибольшим является число ");
Console.WriteLine(max);
